[package]
authors = ["Matthew Brewer <matthew@brewer.sh"]
edition = "2021"
name = "challenges"
license = "MIT"
publish = false
version = "0.1.0"

[[bin]]
name = "day-1-challenge-1"
path = "src/day-1/main.rs"